name: Deploy storybook

on:
  repository_dispatch:
    types: [trigger-storybook]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run predeploy

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/storybook-static
