name: Publish package

on:
  repository_dispatch:
    types: [trigger-publish]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run predeploy

  publish-npm:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: sh scripts/prepublish.sh
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_NPM_TOKEN}}

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: sh scripts/prepublish.sh
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  storybook:
    needs: [build, publish-npm, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/storybook-static
