name: Publish package

on:
  push:
    branches:
      - "main"

jobs:
  bump-version:
    name: "Bump Version"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{github.ref}}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v2"
        with:
          node-version: 16
      - name: "Automated Version Bump"
        id: version-bump
        uses: "phips28/gh-action-bump-version@master"
        with:
          tag-prefix: 'v'
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Output Step"
        env:
          NEW_TAG: ${{steps.version-bump.outputs.newTag}}
        run: echo "new tag $NEW_TAG" && echo $NEW_TAG >> ./tag.txt
      - name: Save tag
        uses: actions/upload-artifact@v2
        with:
          name: tag
          path: ./tag.txt

  build:
    name: "Build"
    needs: bump-version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: npm ci
      - run: npm run build
      - run: npm run predeploy
      - name: Save dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/
      - name: Save storybook build
        uses: actions/upload-artifact@v2
        with:
          name: storybook-build
          path: ./docs/storybook-static

  publish-npm:
    name: "Publish to NPM"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download tag
        uses: actions/download-artifact@v2
        with:
          name: tag
          path: ./tag.txt
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - run: node scripts/update-from-bump.js
      - run: sh scripts/prepublish.sh
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_NPM_TOKEN}}

  publish-gpr:
    name: "Publish to GPR"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Download tag
        uses: actions/download-artifact@v2
        with:
          name: tag
          path: ./tag.txt
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - run: node scripts/update-from-bump.js
      - run: node scripts/convert-to-gpr.js
      - run: sh scripts/prepublish.sh
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  storybook:
    name: "Deploy Storybook"
    needs: [publish-npm, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: storybook-build
          path: ./docs/storybook-static
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          publish_dir: ./docs/storybook-static
