name: Publish package

on:
  repository_dispatch:
    types: [trigger-publish]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - run: cat ./package.json
      - run: npm ci
      - run: npm run build
      - run: npm run predeploy
      - name: Save dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./dist/
      - name: Save storybook build
        uses: actions/upload-artifact@v2
        with:
          name: storybook-build
          path: ./docs/storybook-static

  publish-npm:
    name: "Publish to NPM"
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - run: sh scripts/prepublish.sh
      - run: npm publish dist/
        env:
          NODE_AUTH_TOKEN: ${{secrets.NODE_NPM_TOKEN}}

  publish-gpr:
    name: "Publish to GPR"
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: ./dist
      - run: sh scripts/prepublish.sh
      - run: npm publish ./dist
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  storybook:
    name: "Deploy Storybook"
    needs: [publish-npm, publish-gpr]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist
        uses: actions/download-artifact@v2
        with:
          name: storybook-build
          path: ./docs/storybook-static
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/storybook-static
